import React from 'react'

export const DashBoard = () => {
  return (
    <div className="container">
      <h1>DashBoard Page</h1>
      <br/>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda nostrum, ullam quasi sed dolore vel modi earum harum architecto laborum cum quas aperiam nulla expedita aliquam provident, eveniet pariatur obcaecati sint cumque qui molestias. Natus consequuntur tempora omnis quasi quod, eveniet laboriosam sit neque repellendus placeat fugiat beatae fugit hic est quae sed saepe quo. Quae nulla distinctio cumque mollitia ratione odit ab recusandae doloribus accusamus sapiente velit atque, delectus magni laboriosam laborum quidem molestiae! Necessitatibus maxime corporis mollitia quis illum perspiciatis libero dolorem debitis! Consequatur nesciunt, perferendis totam ab molestiae iusto ipsam nisi rerum nemo placeat ratione at corporis!</p>
      <br />
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda nostrum, ullam quasi sed dolore vel modi earum harum architecto laborum cum quas aperiam nulla expedita aliquam provident, eveniet pariatur obcaecati sint cumque qui molestias. Natus consequuntur tempora omnis quasi quod, eveniet laboriosam sit neque repellendus placeat fugiat beatae fugit hic est quae sed saepe quo. Quae nulla distinctio cumque mollitia ratione odit ab recusandae doloribus accusamus sapiente velit atque, delectus magni laboriosam laborum quidem molestiae! Necessitatibus maxime corporis mollitia quis illum perspiciatis libero dolorem debitis! Consequatur nesciunt, perferendis totam ab molestiae iusto ipsam nisi rerum nemo placeat ratione at corporis!</p>
      <br />
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda nostrum, ullam quasi sed dolore vel modi earum harum architecto laborum cum quas aperiam nulla expedita aliquam provident, eveniet pariatur obcaecati sint cumque qui molestias. Natus consequuntur tempora omnis quasi quod, eveniet laboriosam sit neque repellendus placeat fugiat beatae fugit hic est quae sed saepe quo. Quae nulla distinctio cumque mollitia ratione odit ab recusandae doloribus accusamus sapiente velit atque, delectus magni laboriosam laborum quidem molestiae! Necessitatibus maxime corporis mollitia quis illum perspiciatis libero dolorem debitis! Consequatur nesciunt, perferendis totam ab molestiae iusto ipsam nisi rerum nemo placeat ratione at corporis!</p>
      <br />
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda nostrum, ullam quasi sed dolore vel modi earum harum architecto laborum cum quas aperiam nulla expedita aliquam provident, eveniet pariatur obcaecati sint cumque qui molestias. Natus consequuntur tempora omnis quasi quod, eveniet laboriosam sit neque repellendus placeat fugiat beatae fugit hic est quae sed saepe quo. Quae nulla distinctio cumque mollitia ratione odit ab recusandae doloribus accusamus sapiente velit atque, delectus magni laboriosam laborum quidem molestiae! Necessitatibus maxime corporis mollitia quis illum perspiciatis libero dolorem debitis! Consequatur nesciunt, perferendis totam ab molestiae iusto ipsam nisi rerum nemo placeat ratione at corporis!</p>
      <br />
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda nostrum, ullam quasi sed dolore vel modi earum harum architecto laborum cum quas aperiam nulla expedita aliquam provident, eveniet pariatur obcaecati sint cumque qui molestias. Natus consequuntur tempora omnis quasi quod, eveniet laboriosam sit neque repellendus placeat fugiat beatae fugit hic est quae sed saepe quo. Quae nulla distinctio cumque mollitia ratione odit ab recusandae doloribus accusamus sapiente velit atque, delectus magni laboriosam laborum quidem molestiae! Necessitatibus maxime corporis mollitia quis illum perspiciatis libero dolorem debitis! Consequatur nesciunt, perferendis totam ab molestiae iusto ipsam nisi rerum nemo placeat ratione at corporis!</p>
      <br />
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda nostrum, ullam quasi sed dolore vel modi earum harum architecto laborum cum quas aperiam nulla expedita aliquam provident, eveniet pariatur obcaecati sint cumque qui molestias. Natus consequuntur tempora omnis quasi quod, eveniet laboriosam sit neque repellendus placeat fugiat beatae fugit hic est quae sed saepe quo. Quae nulla distinctio cumque mollitia ratione odit ab recusandae doloribus accusamus sapiente velit atque, delectus magni laboriosam laborum quidem molestiae! Necessitatibus maxime corporis mollitia quis illum perspiciatis libero dolorem debitis! Consequatur nesciunt, perferendis totam ab molestiae iusto ipsam nisi rerum nemo placeat ratione at corporis!</p>
      <br />
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda nostrum, ullam quasi sed dolore vel modi earum harum architecto laborum cum quas aperiam nulla expedita aliquam provident, eveniet pariatur obcaecati sint cumque qui molestias. Natus consequuntur tempora omnis quasi quod, eveniet laboriosam sit neque repellendus placeat fugiat beatae fugit hic est quae sed saepe quo. Quae nulla distinctio cumque mollitia ratione odit ab recusandae doloribus accusamus sapiente velit atque, delectus magni laboriosam laborum quidem molestiae! Necessitatibus maxime corporis mollitia quis illum perspiciatis libero dolorem debitis! Consequatur nesciunt, perferendis totam ab molestiae iusto ipsam nisi rerum nemo placeat ratione at corporis!</p>
      <br />
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda nostrum, ullam quasi sed dolore vel modi earum harum architecto laborum cum quas aperiam nulla expedita aliquam provident, eveniet pariatur obcaecati sint cumque qui molestias. Natus consequuntur tempora omnis quasi quod, eveniet laboriosam sit neque repellendus placeat fugiat beatae fugit hic est quae sed saepe quo. Quae nulla distinctio cumque mollitia ratione odit ab recusandae doloribus accusamus sapiente velit atque, delectus magni laboriosam laborum quidem molestiae! Necessitatibus maxime corporis mollitia quis illum perspiciatis libero dolorem debitis! Consequatur nesciunt, perferendis totam ab molestiae iusto ipsam nisi rerum nemo placeat ratione at corporis!</p>
      <br />
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda nostrum, ullam quasi sed dolore vel modi earum harum architecto laborum cum quas aperiam nulla expedita aliquam provident, eveniet pariatur obcaecati sint cumque qui molestias. Natus consequuntur tempora omnis quasi quod, eveniet laboriosam sit neque repellendus placeat fugiat beatae fugit hic est quae sed saepe quo. Quae nulla distinctio cumque mollitia ratione odit ab recusandae doloribus accusamus sapiente velit atque, delectus magni laboriosam laborum quidem molestiae! Necessitatibus maxime corporis mollitia quis illum perspiciatis libero dolorem debitis! Consequatur nesciunt, perferendis totam ab molestiae iusto ipsam nisi rerum nemo placeat ratione at corporis!</p>
      <br />
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda nostrum, ullam quasi sed dolore vel modi earum harum architecto laborum cum quas aperiam nulla expedita aliquam provident, eveniet pariatur obcaecati sint cumque qui molestias. Natus consequuntur tempora omnis quasi quod, eveniet laboriosam sit neque repellendus placeat fugiat beatae fugit hic est quae sed saepe quo. Quae nulla distinctio cumque mollitia ratione odit ab recusandae doloribus accusamus sapiente velit atque, delectus magni laboriosam laborum quidem molestiae! Necessitatibus maxime corporis mollitia quis illum perspiciatis libero dolorem debitis! Consequatur nesciunt, perferendis totam ab molestiae iusto ipsam nisi rerum nemo placeat ratione at corporis!</p>
      <br />
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda nostrum, ullam quasi sed dolore vel modi earum harum architecto laborum cum quas aperiam nulla expedita aliquam provident, eveniet pariatur obcaecati sint cumque qui molestias. Natus consequuntur tempora omnis quasi quod, eveniet laboriosam sit neque repellendus placeat fugiat beatae fugit hic est quae sed saepe quo. Quae nulla distinctio cumque mollitia ratione odit ab recusandae doloribus accusamus sapiente velit atque, delectus magni laboriosam laborum quidem molestiae! Necessitatibus maxime corporis mollitia quis illum perspiciatis libero dolorem debitis! Consequatur nesciunt, perferendis totam ab molestiae iusto ipsam nisi rerum nemo placeat ratione at corporis!</p>
      <br />
        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda nostrum, ullam quasi sed dolore vel modi earum harum architecto laborum cum quas aperiam nulla expedita aliquam provident, eveniet pariatur obcaecati sint cumque qui molestias. Natus consequuntur tempora omnis quasi quod, eveniet laboriosam sit neque repellendus placeat fugiat beatae fugit hic est quae sed saepe quo. Quae nulla distinctio cumque mollitia ratione odit ab recusandae doloribus accusamus sapiente velit atque, delectus magni laboriosam laborum quidem molestiae! Necessitatibus maxime corporis mollitia quis illum perspiciatis libero dolorem debitis! Consequatur nesciunt, perferendis totam ab molestiae iusto ipsam nisi rerum nemo placeat ratione at corporis!</p>
      <br />
      
    </div>
  )
}
